import type { Metadata } from "next";
import "./globals.css";
import { NavbarDemo } from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
        className={` antialiased`}
      >
        <NavbarDemo />
        <main className="mt-14">
        {children}
        </main>
      </body>
    </html>
  );
}
